spring.application.name=auth-service

server.port=8082

# JWT secret
jwt.secret=MinhaChaveSecretaSuperSegura
jwt.expiration=3600000

# Configuração do Feign para chamar o user-service
user-service.url=http://localhost:8081/api/users
