version: '3.8'
services:
  db:
    image: postgres:17
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: user_pass
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  user-service:
    build: .
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: user_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - db

volumes:
  user_data:
